[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
freya = "0.3.4"
vault = { path = "../vault" }
types = { path = "../types" }
config = { path = "../config" }
log = "0.4.27"
serde = "1.0.219"
serde_yaml = "0.9.34"
